version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      timezone: 'US/Mountain'
    open-pull-requests-limit: 1
    groups:
      npm:
        patterns:
          - '*'
